version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nq]777rp),x%EpY>P9J9
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    command: [
      "--character-set-server=utf8",
      "--default-time-zone=+8:00",
    ]
    restart: always
    volumes:
      - "/data/docker/mysql/data:/var/lib/mysql"
      - "/data/docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/docker/nginx/html:/usr/share/nginx/html"
      - "/data/docker/nginx/conf:/etc/nginx/conf.d"
      - "/data/docker/nginx/log:/var/log/nginx"
    depends_on:
      - mysql
